create table public.ohd_s_colors (
  color_id bigint generated by default as identity not null,
  color_name character varying(100) null,
  constraint ohd_s_colors_pkey primary key (color_id)
) TABLESPACE pg_default;


create table public.ohd_s_insulation_type (
  ins_type_id bigint generated by default as identity not null,
  type_name character varying(100) null,
  r_value character varying(100) null,
  model character varying(100) null,
  construct character varying(100) null,
  steel character varying(100) null,
  insulation character varying(100) null,
  price_persqft numeric(18, 2) null,
  premium_color_add_on numeric(18, 2) null,
  price_premium_color numeric(18, 2) null,
  wood_grain_color_add_on numeric(18, 2) null,
  price_wood_grain_color numeric(18, 2) null,
  constraint ohd_s_insulation_type_pkey primary key (ins_type_id)
) TABLESPACE pg_default;


create table public.ohd_s_statuses (
  status_id bigint generated always as identity not null,
  name text null,
  description text null,
  constraint ohd_s_statuses_pkey primary key (status_id),
  constraint ohd_s_statuses_name_key unique (name)
) TABLESPACE pg_default;


create table public.ohd_s_openers (
  opener_id bigint generated by default as identity not null,
  opener_name character varying(100) null,
  opener_price numeric(18, 2) null,
  constraint ohd_s_openers_pkey primary key (opener_id)
) TABLESPACE pg_default;

create table public.ohd_s_track_options (
  track_id bigint generated by default as identity not null,
  track_name character varying(100) null,
  track_price numeric(18, 2) null,
  constraint ohd_s_track_options_pkey primary key (track_id)
) TABLESPACE pg_default;

create table public.ohd_s_pane_style (
  pane_style_id bigint generated by default as identity not null,
  style_name character varying(100) null,
  constraint ohd_s_pane_style_pkey primary key (pane_style_id)
) TABLESPACE pg_default;


create table public.ohd_s_trip_rates (
  trip_id bigint generated by default as identity not null,
  label character varying(100) null,
  rate numeric(18, 2) null,
  constraint ohd_s_trip_rates_pkey primary key (trip_id)
) TABLESPACE pg_default;


create table public.ohd_s_windows_type (
  windows_type_id bigint generated by default as identity not null,
  windows_type character varying(100) null,
  windows_glass_category character varying(100) null,
  windows_price numeric(18, 2) null,
  constraint ohd_s_windows_type_pkey primary key (windows_type_id)
) TABLESPACE pg_default;


create table public.ohd_s_windows_type (
  windows_type_id bigint generated by default as identity not null,
  windows_type character varying(100) null,
  windows_glass_category character varying(100) null,
  windows_price numeric(18, 2) null,
  constraint ohd_s_windows_type_pkey primary key (windows_type_id)
) TABLESPACE pg_default;


create table public.ohd_m_project_extras (
  extra_id bigint generated by default as identity not null,
  proj_id bigint not null,
  name character varying(100) null,
  quantity integer null,
  unit_price numeric(18, 2) null,
  constraint ohd_m_project_extras_pkey primary key (extra_id),
  constraint fk_ohd_extra_project foreign KEY (proj_id) references ohd_t_projects (proj_id)
) TABLESPACE pg_default;


create table public.ohd_t_project_extra_snapshot (
  snapshot_extra_id bigint generated by default as identity not null,
  project_snapshot_id bigint not null,
  extra_name character varying(100) null,
  quantity integer null,
  unit_price numeric(18, 2) null,
  total_price numeric(18, 2) null,
  constraint ohd_t_project_extra_snapshot_pkey primary key (snapshot_extra_id),
  constraint fk_ohd_extra_snapshot foreign KEY (project_snapshot_id) references ohd_t_project_snapshot (project_snapshot_id)
) TABLESPACE pg_default;


create table public.ohd_t_project_extra_snapshot (
  snapshot_extra_id bigint generated by default as identity not null,
  project_snapshot_id bigint not null,
  extra_name character varying(100) null,
  quantity integer null,
  unit_price numeric(18, 2) null,
  total_price numeric(18, 2) null,
  constraint ohd_t_project_extra_snapshot_pkey primary key (snapshot_extra_id),
  constraint fk_ohd_extra_snapshot foreign KEY (project_snapshot_id) references ohd_t_project_snapshot (project_snapshot_id)
) TABLESPACE pg_default;


create table public.ohd_t_project_snapshot (
  project_snapshot_id bigint generated by default as identity not null,
  proj_id bigint null,
  item_id bigint null,
  quote_number character varying(100) null,
  project_name character varying(100) null,
  project_address text null,
  trip_label character varying(100) null,
  trip_rate numeric(18, 2) null,
  quantity integer null,
  width numeric(10, 2) null,
  height numeric(10, 2) null,
  color_opacity integer null,
  color_id bigint null,
  color_name character varying(100) null,
  pane_style_id bigint null,
  pane_style_name character varying(100) null,
  ins_type_id bigint null,
  type_name character varying(100) null,
  r_value character varying(100) null,
  model character varying(100) null,
  construct character varying(100) null,
  steel character varying(100) null,
  insulation character varying(100) null,
  price_persqft numeric(18, 2) null,
  premium_color_add_on numeric(18, 2) null,
  price_premium_color numeric(18, 2) null,
  wood_grain_color_add_on numeric(18, 2) null,
  price_wood_grain_color numeric(18, 2) null,
  track_name character varying(100) null,
  track_price numeric(18, 2) null,
  opener_id bigint null,
  opener_name character varying(100) null,
  opener_price numeric(18, 2) null,
  opener_quantity integer null,
  windows_type_id bigint null,
  windows_type character varying(100) null,
  windows_glass_category character varying(100) null,
  windows_price numeric(18, 2) null,
  windows_quantity integer null,
  estprice_dimension numeric(18, 2) null,
  estprice_pane_style_door numeric(18, 2) null,
  estprice_insulation numeric(18, 2) null,
  estprice_windows numeric(18, 2) null,
  discount numeric(18, 2) null,
  downpayment numeric(18, 2) null,
  item_total numeric(18, 2) null,
  project_price_subtotal numeric(18, 2) null,
  project_price_overall_total numeric(18, 2) null,
  snapshot_created_at timestamp without time zone null default now(),
  snapshot_created_by bigint null,
  snapshot_version character varying(100) null,
  constraint ohd_t_project_snapshot_pkey primary key (project_snapshot_id)
) TABLESPACE pg_default;


create table public.ohd_t_projects (
  proj_id bigint generated by default as identity not null,
  quote_number character varying(100) null,
  project_name character varying(100) null,
  project_address text null,
  request_link text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  created_by bigint null,
  updated_by bigint null,
  discount numeric(18, 2) null,
  downpayment numeric(18, 2) null,
  price_subtotal numeric(18, 2) null,
  trip_id bigint null,
  price_overall_total numeric(18, 2) null,
  status_id bigint null,
  constraint ohd_t_projects_pkey primary key (proj_id),
  constraint fk_ohd_project_createdby foreign KEY (created_by) references psb_s_user (user_id),
  constraint fk_ohd_project_trip foreign KEY (trip_id) references ohd_s_trip_rates (trip_id),
  constraint fk_ohd_project_updatedby foreign KEY (updated_by) references psb_s_user (user_id),
  constraint ohd_t_projects_status_id_fkey foreign KEY (status_id) references ohd_s_statuses (status_id) on update CASCADE on delete set null
) TABLESPACE pg_default;


create table public.ohd_s_statuses (
  status_id bigint generated always as identity not null,
  name text null,
  description text null,
  constraint ohd_s_statuses_pkey primary key (status_id),
  constraint ohd_s_statuses_name_key unique (name)
) TABLESPACE pg_default;