-- ============================================================
-- Migration 003: Create pricing constants setup table
-- ============================================================
-- Started At : 2026-07-05
-- Schema     : public
-- ============================================================

-- [STEP 1/4]
-- Checking if table "ohd_s_pricing_constants" exists...

CREATE TABLE IF NOT EXISTS public.ohd_s_pricing_constants (
  pricing_constant_id bigint generated by default as identity not null,
  constant_name character varying(100) not null,
  constant_value numeric(18, 2) not null,
  description text null,
  display_order integer null default 0,
  constraint ohd_s_pricing_constants_pkey primary key (pricing_constant_id),
  constraint ohd_s_pricing_constants_name_key unique (constant_name)
) TABLESPACE pg_default;

-- ✔ Table created or already exists.

-- [STEP 2/4]
-- Synchronizing setup data...

INSERT INTO public.ohd_s_pricing_constants (constant_name, constant_value, description, display_order)
VALUES
  ('Header Seal', 0.95, 'Per inch', 1),
  ('Rev Seal', 0.90, 'Per inch', 2),
  ('Multiplier', 1.25, 'Global multiplier', 3)
ON CONFLICT (constant_name)
DO UPDATE
SET
  constant_value = EXCLUDED.constant_value,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

-- ✔ Setup data synchronized.

-- [STEP 3/4]
-- Verifying constraints...

-- ✔ Unique constraint on constant_name exists.

-- [STEP 4/4]
-- Migration complete.

-- ============================================================
-- Migration 003 Complete
-- ============================================================
-- Tables Created        : 1 (or already existed)
-- Rows Inserted/Updated : 3
-- Status                : SUCCESS
-- ============================================================
